# Generated by Django 5.1.1 on 2024-10-17 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("member", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("author", models.CharField(max_length=20)),
                ("cheonggu", models.CharField(max_length=20)),
                ("publisher", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Community_by_period",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Community_by_book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("body", models.CharField(max_length=200)),
                ("period", models.CharField(max_length=30)),
                ("status", models.CharField(max_length=10)),
                ("book_title", models.CharField(max_length=20, null=True)),
                ("book_author", models.CharField(max_length=20, null=True)),
                ("book_cheonggu", models.CharField(max_length=20, null=True)),
                ("book_publisher", models.CharField(max_length=20, null=True)),
                (
                    "leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leader",
                        to="member.customuser",
                    ),
                ),
                (
                    "participant",
                    models.ManyToManyField(
                        related_name="participant", to="member.customuser"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User_page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("page", models.IntegerField()),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="community.community_by_book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="member.customuser",
                    ),
                ),
            ],
        ),
    ]
