# Generated by Django 5.1.4 on 2024-12-25 08:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupboard',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participated_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
