# Generated by Django 5.1.1 on 2024-10-17 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=20)),
                ("gender", models.CharField(max_length=10)),
                ("age", models.IntegerField()),
                ("region", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="UserBooklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("body", models.CharField(max_length=1000)),
                ("star", models.IntegerField()),
                ("book_title", models.CharField(max_length=20)),
                ("book_author", models.CharField(max_length=20)),
                ("book_cheonggu", models.CharField(max_length=20)),
                ("book_publisher", models.CharField(max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booklist",
                        to="member.customuser",
                    ),
                ),
            ],
        ),
    ]
